[program:p2p-horizon]
process_name=%(program_name)s
command=php /var/www/p2p.processing/artisan horizon
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/p2p.processing/storage/logs/horizon.log
stopwaitsecs=3600
